### PR TITLE
[12.0] new module remove_odoo_enterprise

### PR DESCRIPTION
**Pull request by levkar**
This is a new module with new name removing enterprise modules and settings. 

Includes the functionality of res_config_settings_enterprise_remove module.

### CODE REVIEW

**Review by eLBati — APPROVED** [review]

**Comment by astirpe** [comment]
Is it possible to preserve the commit history from `res_config_settings_enterprise_remove` ?

**Comment by levkar** [comment]
commit history included. oca clabot started complaining again.

**Comment by levkar** [comment]
clabot is complaining about bret wood!

**Comment by pedrobaeza** [comment]
@levkar we are handling this in https://github.com/OCA/oca-github-bot/issues/28

**Review by astirpe — APPROVED** [review]

**Comment by astirpe** [comment]
Please fix the Travis error

**Comment by astirpe** [comment]
FYI: https://github.com/OCA/multi-company/pull/119#discussion_r269025232

**Comment by emagdalenaC2i** [comment]
@levkar and @astirpe This PR superseed #7 and rename the module?

**Comment by astirpe** [comment]
@emagdalenaC2i yes, correct.

**Review by Martronic-SA — APPROVED** [review]
Tested and working as expected.

**Review by sergiocorato — APPROVED** [review]
LGTM

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by mileo — APPROVED** [review]

**Comment by astirpe** [comment]
@pedrobaeza there are 6 approvals here. Can we merge this PR?

**Pull request merged**
