### PR TITLE
[12.0][MIG] res_config_settings_enterprise_remove

### PR DESCRIPTION
**Pull request by astirpe**
https://github.com/OCA/server-brand/issues/6

### CODE REVIEW

**Review by eLBati — APPROVED** [review]

**Comment by eLBati** [comment]
Hi @astirpe , could you also add this https://github.com/OCA/server-brand/pull/8/commits/a017bc5aed10f92933f37d9399e53a673a22081a ?

**Comment by pedrobaeza** [comment]
The problem with `<delete>` records is that they give a warning when the record is not found, so updating 2 times the module results in an ugly log, but right now I can't think in a better solution.

**Comment by astirpe** [comment]
@eLBati @pedrobaeza as stated in the description on the readme, this module is not meant to delete the enterprise modules from the modules list. It's only meant to remove them from the config settings view.  I would rather create a separate module for that. Or discuss the possibility to modify this module, but in a separate PR. I honestly don't like to introduce warnings in the log when doing an update all. So if it's OK for you, I would keep this PR as it is: a pure porting of the module.

**Comment by pedrobaeza** [comment]
OK, let's keep this PR as is, but introduce later that.

**Comment by eLBati** [comment]
Ok

**Comment by eLBati** [comment]
Ok

**Comment by eLBati** [comment]
Ok

**Comment by eLBati** [comment]
Ok

**Comment by eLBati** [comment]
Ok

**Comment by eLBati** [comment]
Ok

**Comment by levkar** [comment]
I made a simple 12.0 migration PR https://github.com/OCA/server-brand/pull/11 before i noticed this PR.  

Here is the way to avoid warning messages:

`` 
<delete model="ir.module.module" search="[('to_buy', '=', True)]"/>
``

But the name of the module ("res_config_settings_enterprise_remove") can be misleading. Maybe it should be another module named "module_enterprise_remove" ? Or a new module named "enterprise_remove" can be introduced to include both functionalities. I can cancel my PR and/or help with a new PR. Let me know what you think. 

One last question, why don't we have modules in this repo with auto_install=True?

**Comment by astirpe** [comment]
@levkar thank you for the tip! I agree with you, an extra module is needed. Or an alternative "enterprise_remove" module would be great, but this solution will prevent the user to install enterprise modules! Both proposals are fine to me.
Would you like to go ahead and open a PR? Let me know...

**Comment by levkar** [comment]
@astirpe I created a new pull request #12.

**Comment by astirpe** [comment]
Closing in favour of #12

**Pull request closed without merging**
