### PR TITLE
[13.0][FIX] remove_odoo_enterprise: fix access rights error with portal user

### PR DESCRIPTION
**Pull request by astirpe**
Fixes https://github.com/OCA/server-brand/issues/27 ?

### CODE REVIEW

**Comment by zackleeuk** [comment]
> Fixes #27 ?

nope, it still have the same problem.

**Comment by sergioeix** [comment]
I checked this fix and seems that works, now I am not getting ERROR 403, I will check it in deep and let you know, good work astirpe.
Ty

**Comment by zackleeuk** [comment]
I tested it, it seems all good now.
Many thanks.@astirpe

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
