### PR TITLE
[MIG][15.0] disable_odoo_online

### PR DESCRIPTION
**Pull request by vincent-hatakeyama**
Standard migration

Updated the documentation to indicate the removal of user menu items ; that was already done in the previous version.

The user menu changes are now done in javascript as there is no template used in the web module anymore.

### CODE REVIEW

**Comment by vincent-hatakeyama** [comment]
Concerning the eslint error, I think it is incorrect. I used the new way of declaring odoo modules (for example in [addons/web/static/src/webclient/user_menu/user_menu_items.js](https://github.com/odoo/odoo/blob/15.0/addons/web/static/src/webclient/user_menu/user_menu_items.js#L2); I believe the linter is unable to parse that correctly.

I followed the [standard migration process](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0), so I do not know why the bot is complaining about those authors while it did not complain in #35

**Comment by pedrobaeza** [comment]
Have you done this

```
If you migrate some .js file to an ES module (they start with /** @odoo-module **/), rename the file to finish with .esm.js (rename also the assets) to enable ESLint compatibility.
```

?

**Comment by vincent-hatakeyama** [comment]
Thanks, changing the file name fixes that issues.

I’ve disabled an eslint rule because it is needed to have the module work. If there’s another way to do it, I am not aware of it.

**Review by jguenat — APPROVED** [review]
LGTM, thanks

**Pull request merged**
