### PR TITLE
[18.0][MIG] disable_odoo_online: Migration to 18.0

### PR DESCRIPTION
**Pull request by PauMAVA**
- Bump version to `18.0.1.0.0`
- Remove `/** @odoo-module **/` from `user_menu_items.esm.js` since it's no longer needed

No further changes needed. See:
https://github.com/odoo/odoo/blob/18.0/addons/web/static/src/webclient/user_menu/user_menu_items.js#L154
https://github.com/odoo/odoo/blob/18.0/addons/mail/models/update.py#L77
https://github.com/odoo/odoo/blob/18.0/odoo/addons/base/views/ir_module_views.xml#L229

---------------
@Level4Tech

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check CI

**Comment by PauMAVA** [comment]
Buenas @pedrobaeza faltan tests tanto en `disable_odoo_online` como en `portal_odoo_debranding`. 

```
WARNING odoo odoo.tests.result: 0 failed, 0 error(s) of 0 tests when loading database 'odoo' 
```

Tampoco había en la 17.0.

Miro de implementar algunos.

**Comment by pedrobaeza** [comment]
Please talk in this international repo in English. We can talk in Spanish in OCA/l10n-spain.

Yeah, now the warnings give red in CI. You can add a dummy test in this case as a workaround.

**Comment by PauMAVA** [comment]
Quick question, I see the new PWA menu and also config section. I don't see any reference to it being part of enterprise and It fully works as expected. At the same time I know there is the OCA PWA repo the OCA PWA will then be deprecated?

imagen
imagen
imagen


In this case we should obviously not hide the PWA features. I will remove this line that I previously added:

```
registry.category("user_menuitems").remove("install_pwa");
```

**Comment by pedrobaeza** [comment]
Yes, PWA is something that shouldn't be hidden.

**Comment by PauMAVA** [comment]
Dummy tests as a workaround implemented in both disable_odoo_online and portal_odoo_debranding PRs.

**Review by houssine78 — APPROVED** [review]
LGTM

**Review by celm1990 — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
