### PR TITLE
[16.0][MIG] disable_odoo_online: Migration to 16.0

### PR DESCRIPTION
**Pull request by remi-filament**

### CODE REVIEW

**Review by bealdav — APPROVED** [review]
Nice and thanks

**Review by hparfr — APPROVED** [review]
module looks ok
but there is also some unrelated changes on .copier-answers.yml and .pre-commit-config.yml...

**Comment by remi-filament** [comment]
> but there is also some unrelated changes on .copier-answers.yml and .pre-commit-config.yml...

> there is also some unrelated changes on .copier-answers.yml and .pre-commit-config.yml...

You are right, because of #63, I have just rebased since it was merged earlier today so it does not appear in list of commits anymore !
Thanks

**Comment by hparfr** [comment]
Thanks; it's ready  to be merged now

**Review by astirpe — APPROVED** [review]

**Pull request merged**
