### PR TITLE
[16.0][MIG] portal_odoo_debranding: Migration to 16.0

### PR DESCRIPTION
**Pull request by remi-filament**

### CODE REVIEW

**Review by bealdav — APPROVED** [review]
LGTM, no changes according to last commit

**Review by hparfr — APPROVED** [review]

**Comment by hparfr** [comment]
there is also some unrelated changes on .copier-answers.yml and .pre-commit-config.yml...

**Comment by remi-filament** [comment]
> there is also some unrelated changes on .copier-answers.yml and .pre-commit-config.yml...

You are right, because of #63, I have just rebased since it was merged earlier today so it does not appear in list of commits anymore !
Thanks

**Comment by hparfr** [comment]
Thanks; it's ready  to be merged now

**Pull request merged**
